[workspace]

members = ["load_census_data", "sim", "run", "visualisation"]

resolver = "2"

[profile.dev]
opt-level = 3
debug = 1
incremental = true
lto = "thin"
debug-assertions = false
codegen-units = 128