[package]
name = "sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
load_census_data = { path = "../load_census_data" }

anyhow = "1.0"
csv = "1.1.6"
enum-map = "1.1.1"
geo-types = "0.7.2"
log = "0.4"
rand = "0.8.4"
serde = "1.0"
serde_plain = "1.0"
shapefile = { version = "0.3.0", features = ["geo-types"] }
uuid = { version = "0.8", features = ["v4"] }
