[package]
name = "load_census_data"
version = "0.1.0"
edition = "2018"
authors = ["Sam Ralph"]

[dependencies]
csv = "1.1.6"
enum-map = "1.1.1"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.8.4"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_plain = "1.0.0"
strum = "0.23"
strum_macros = "0.23"